preload = /home/sunniez/wallpapers/trap/trap_wall1.jxl
preload = /home/sunniez/wallpapers/trap/trap_wall2.jxl
preload = /home/sunniez/wallpapers/trap/trap_wall3.jxl
preload = /home/sunniez/wallpapers/trap/trap_wall4.jxl
preload = /home/sunniez/wallpapers/trap/trap_wall5.jxl

preload = /home/sunniez/wallpapers/bunny/bunny_wall1.jxl
preload = /home/sunniez/wallpapers/bunny/bunny_wall2.jxl
preload = /home/sunniez/wallpapers/bunny/bunny_wall3.jxl
preload = /home/sunniez/wallpapers/bunny/bunny_wall4.jxl
preload = /home/sunniez/wallpapers/bunny/bunny_wall5.jxl

splash = false

wallpaper {
    monitor = eDP-1
    path = /home/sunniez/wallpapers/trap/trap_wall5.jxl
    fit_mode = cover
}
